version: "2"
linters:
  default: standard
  enable:
    - bodyclose
    - errorlint
    - gosec
    - misspell
    - nilerr
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - unconvert
  settings:
    gosec:
      excludes: [G104]
  exclusions:
    paths: [gen]
formatters:
  enable: [gofmt, goimports]
